function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_back_button
	global.__objectDepths[1] = -2; // obj_congratulations
	global.__objectDepths[2] = -100; // obj_pause
	global.__objectDepths[3] = -5; // obj_pause_button
	global.__objectDepths[4] = 0; // obj_title
	global.__objectDepths[5] = 0; // obj_leaderboard_button
	global.__objectDepths[6] = 0; // obj_achievement_button
	global.__objectDepths[7] = 0; // obj_settings_button
	global.__objectDepths[8] = 0; // obj_play_button
	global.__objectDepths[9] = 0; // obj_init
	global.__objectDepths[10] = 0; // obj_shop_cart
	global.__objectDepths[11] = 0; // obj_bat
	global.__objectDepths[12] = -1; // obj_controller
	global.__objectDepths[13] = -2; // obj_get_coin
	global.__objectDepths[14] = 0; // obj_ball
	global.__objectDepths[15] = 0; // obj_wall_h
	global.__objectDepths[16] = 0; // obj_wall_v
	global.__objectDepths[17] = -1; // obj_score_1000
	global.__objectDepths[18] = 0; // obj_shoot
	global.__objectDepths[19] = 0; // obj_firework
	global.__objectDepths[20] = 0; // obj_shield_protection
	global.__objectDepths[21] = 0; // obj_block
	global.__objectDepths[22] = 0; // obj_forestgreen_block
	global.__objectDepths[23] = 0; // obj_blue_block
	global.__objectDepths[24] = 0; // obj_yellow_block
	global.__objectDepths[25] = 0; // obj_brown_block
	global.__objectDepths[26] = 0; // obj_green_block
	global.__objectDepths[27] = 0; // obj_white_block
	global.__objectDepths[28] = 0; // obj_basic_block
	global.__objectDepths[29] = 0; // obj_red_block
	global.__objectDepths[30] = 0; // obj_black_block
	global.__objectDepths[31] = 0; // obj_lavender_block
	global.__objectDepths[32] = 0; // obj_dimgray_block
	global.__objectDepths[33] = 0; // obj_deeppink_block
	global.__objectDepths[34] = 0; // obj_brown1_block
	global.__objectDepths[35] = 0; // obj_pink_block
	global.__objectDepths[36] = 0; // obj_dimgray1_block
	global.__objectDepths[37] = 0; // obj_black1_block
	global.__objectDepths[38] = 0; // obj_purple_block
	global.__objectDepths[39] = -2; // obj_gem1
	global.__objectDepths[40] = -2; // obj_longbat_item
	global.__objectDepths[41] = -2; // obj_shortbat_item
	global.__objectDepths[42] = -2; // obj_metalball_item
	global.__objectDepths[43] = -2; // obj_coin
	global.__objectDepths[44] = -2; // obj_magnet
	global.__objectDepths[45] = -2; // obj_random
	global.__objectDepths[46] = -2; // obj_shield
	global.__objectDepths[47] = -2; // obj_live
	global.__objectDepths[48] = -2; // obj_gun
	global.__objectDepths[49] = -2; // obj_slow
	global.__objectDepths[50] = -2; // obj_fast
	global.__objectDepths[51] = -2; // obj_split
	global.__objectDepths[52] = -2; // obj_counter
	global.__objectDepths[53] = -2; // obj_achievemet
	global.__objectDepths[54] = -2; // obj_blocks_fall
	global.__objectDepths[55] = 0; // obj_draw_level
	global.__objectDepths[56] = 0; // obj_select_stage
	global.__objectDepths[57] = 0; // obj_world_name
	global.__objectDepths[58] = 0; // obj_stage1
	global.__objectDepths[59] = 0; // obj_stage2
	global.__objectDepths[60] = 0; // obj_menu_ctrl
	global.__objectDepths[61] = 0; // obj_menu_next
	global.__objectDepths[62] = 0; // obj_menu_prev
	global.__objectDepths[63] = 0; // obj_menu_move
	global.__objectDepths[64] = 0; // obj_menu_current
	global.__objectDepths[65] = 100; // obj_draw_back
	global.__objectDepths[66] = 0; // obj_bgmusic_title
	global.__objectDepths[67] = -1; // obj_sliderball
	global.__objectDepths[68] = -1; // obj_sliderbar_music
	global.__objectDepths[69] = -1; // obj_sliderbar_sfx
	global.__objectDepths[70] = 0; // obj_vol_down
	global.__objectDepths[71] = 0; // obj_music_down
	global.__objectDepths[72] = 0; // obj_vol_up
	global.__objectDepths[73] = 0; // obj_music_up
	global.__objectDepths[74] = 0; // obj_sf_title
	global.__objectDepths[75] = 0; // obj_settings_title
	global.__objectDepths[76] = 0; // obj_home_button
	global.__objectDepths[77] = 0; // obj_gameover_title
	global.__objectDepths[78] = 0; // obj_yourscore
	global.__objectDepths[79] = 0; // obj_highscore
	global.__objectDepths[80] = 0; // obj_restart_button
	global.__objectDepths[81] = 0; // obj_settings
	global.__objectDepths[82] = 0; // obj_levels_button
	global.__objectDepths[83] = 0; // obj_hud_score
	global.__objectDepths[84] = 0; // obj_packclear
	global.__objectDepths[85] = 0; // obj_gamedone
	global.__objectDepths[86] = -99999999; // obj_mb_bg
	global.__objectDepths[87] = -999999999; // obj_mb_ok_btn
	global.__objectDepths[88] = -999999999; // obj_mb_cancel_btn
	global.__objectDepths[89] = 0; // obj_purchase_list
	global.__objectDepths[90] = 0; // obj_iap_trait
	global.__objectDepths[91] = 0; // obj_inapp_list1
	global.__objectDepths[92] = 0; // obj_inapp_list2
	global.__objectDepths[93] = 0; // obj_inapp_list3
	global.__objectDepths[94] = 0; // obj_inapp_list4
	global.__objectDepths[95] = 0; // obj_inapp_list5
	global.__objectDepths[96] = 0; // obj_more_coins
	global.__objectDepths[97] = 0; // obj_social


	global.__objectNames[0] = "obj_back_button";
	global.__objectNames[1] = "obj_congratulations";
	global.__objectNames[2] = "obj_pause";
	global.__objectNames[3] = "obj_pause_button";
	global.__objectNames[4] = "obj_title";
	global.__objectNames[5] = "obj_leaderboard_button";
	global.__objectNames[6] = "obj_achievement_button";
	global.__objectNames[7] = "obj_settings_button";
	global.__objectNames[8] = "obj_play_button";
	global.__objectNames[9] = "obj_init";
	global.__objectNames[10] = "obj_shop_cart";
	global.__objectNames[11] = "obj_bat";
	global.__objectNames[12] = "obj_controller";
	global.__objectNames[13] = "obj_get_coin";
	global.__objectNames[14] = "obj_ball";
	global.__objectNames[15] = "obj_wall_h";
	global.__objectNames[16] = "obj_wall_v";
	global.__objectNames[17] = "obj_score_1000";
	global.__objectNames[18] = "obj_shoot";
	global.__objectNames[19] = "obj_firework";
	global.__objectNames[20] = "obj_shield_protection";
	global.__objectNames[21] = "obj_block";
	global.__objectNames[22] = "obj_forestgreen_block";
	global.__objectNames[23] = "obj_blue_block";
	global.__objectNames[24] = "obj_yellow_block";
	global.__objectNames[25] = "obj_brown_block";
	global.__objectNames[26] = "obj_green_block";
	global.__objectNames[27] = "obj_white_block";
	global.__objectNames[28] = "obj_basic_block";
	global.__objectNames[29] = "obj_red_block";
	global.__objectNames[30] = "obj_black_block";
	global.__objectNames[31] = "obj_lavender_block";
	global.__objectNames[32] = "obj_dimgray_block";
	global.__objectNames[33] = "obj_deeppink_block";
	global.__objectNames[34] = "obj_brown1_block";
	global.__objectNames[35] = "obj_pink_block";
	global.__objectNames[36] = "obj_dimgray1_block";
	global.__objectNames[37] = "obj_black1_block";
	global.__objectNames[38] = "obj_purple_block";
	global.__objectNames[39] = "obj_gem1";
	global.__objectNames[40] = "obj_longbat_item";
	global.__objectNames[41] = "obj_shortbat_item";
	global.__objectNames[42] = "obj_metalball_item";
	global.__objectNames[43] = "obj_coin";
	global.__objectNames[44] = "obj_magnet";
	global.__objectNames[45] = "obj_random";
	global.__objectNames[46] = "obj_shield";
	global.__objectNames[47] = "obj_live";
	global.__objectNames[48] = "obj_gun";
	global.__objectNames[49] = "obj_slow";
	global.__objectNames[50] = "obj_fast";
	global.__objectNames[51] = "obj_split";
	global.__objectNames[52] = "obj_counter";
	global.__objectNames[53] = "obj_achievemet";
	global.__objectNames[54] = "obj_blocks_fall";
	global.__objectNames[55] = "obj_draw_level";
	global.__objectNames[56] = "obj_select_stage";
	global.__objectNames[57] = "obj_world_name";
	global.__objectNames[58] = "obj_stage1";
	global.__objectNames[59] = "obj_stage2";
	global.__objectNames[60] = "obj_menu_ctrl";
	global.__objectNames[61] = "obj_menu_next";
	global.__objectNames[62] = "obj_menu_prev";
	global.__objectNames[63] = "obj_menu_move";
	global.__objectNames[64] = "obj_menu_current";
	global.__objectNames[65] = "obj_draw_back";
	global.__objectNames[66] = "obj_bgmusic_title";
	global.__objectNames[67] = "obj_sliderball";
	global.__objectNames[68] = "obj_sliderbar_music";
	global.__objectNames[69] = "obj_sliderbar_sfx";
	global.__objectNames[70] = "obj_vol_down";
	global.__objectNames[71] = "obj_music_down";
	global.__objectNames[72] = "obj_vol_up";
	global.__objectNames[73] = "obj_music_up";
	global.__objectNames[74] = "obj_sf_title";
	global.__objectNames[75] = "obj_settings_title";
	global.__objectNames[76] = "obj_home_button";
	global.__objectNames[77] = "obj_gameover_title";
	global.__objectNames[78] = "obj_yourscore";
	global.__objectNames[79] = "obj_highscore";
	global.__objectNames[80] = "obj_restart_button";
	global.__objectNames[81] = "obj_settings";
	global.__objectNames[82] = "obj_levels_button";
	global.__objectNames[83] = "obj_hud_score";
	global.__objectNames[84] = "obj_packclear";
	global.__objectNames[85] = "obj_gamedone";
	global.__objectNames[86] = "obj_mb_bg";
	global.__objectNames[87] = "obj_mb_ok_btn";
	global.__objectNames[88] = "obj_mb_cancel_btn";
	global.__objectNames[89] = "obj_purchase_list";
	global.__objectNames[90] = "obj_iap_trait";
	global.__objectNames[91] = "obj_inapp_list1";
	global.__objectNames[92] = "obj_inapp_list2";
	global.__objectNames[93] = "obj_inapp_list3";
	global.__objectNames[94] = "obj_inapp_list4";
	global.__objectNames[95] = "obj_inapp_list5";
	global.__objectNames[96] = "obj_more_coins";
	global.__objectNames[97] = "obj_social";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
